# 工作流程名称
name: Blog CI
on:
    push:
        branches:
            - master
        paths:
            - 'version/README.md'


# 触发构建动作
#    push:
#        # 触发构建分支[默认分支]
#        branches: [ $default-branch ]
#    pull_request:


# 作业是在同一运行服务器上执行的一组步骤
jobs:
    # 作业名称
    deploy:
        # 运行器（这里是Ubuntu系统）
        runs-on: ubuntu-latest
        # 作业名称（同deploy）
        name: Deploy
        # 步骤是可以在作业中运行命令的单个任务
        # 步骤可以是操作或 shell 命令
        steps:
            # 检出推送的代码
            - name: Checkout
              uses: actions/checkout@v2
            # 安装node
            - uses: actions/setup-node@v1
            # 安装项目依赖
            - name: Install Dependencies
              run: npm install
              env:
                EMAILPASS: ${{secrets.EMAILPASS}}
            # 发布到云开发
            - name: Deploy to Tencent CloudBase
              uses: TencentCloudBase/cloudbase-action@v2
              with:
              # 以下参数配置于 github secrets
                 secretId: ${{secrets.SECRETID}}
                 secretKey: ${{secrets.SECRETKEY}}
                 envId: ${{secrets.ENV_ID}}
                 SENDEMAIL: ${{secrets.SENDEMAIL}}
                 TOEMAIL: ${{secrets.TOEMAIL}}
            # 发送邮件
            - name: Sene Email
              env:
                EMAILPASS: ${{secrets.EMAILPASS}}
              run:  npm run send
